from poly import *

p1 = Polynomial([1, 2, 3])
print(p1)
print()
p2 = Polynomial([100, 200])
print(p1.add(p2))
print()
print(p1 + p2)
print()
print(p1(1))
print()
print(p1(-1))
print()
print((p1 + p2)(10))
print()
print(p1.mul(p1))
print()
print(p1 * p1)
print()
print(p1 * p2 + p1)
print()
print(p1.roots())
print()
print(p2.roots())
print()
p3 = Polynomial([3, 2, -1])
print(p3.roots())
print()
print((p1 * p1).roots())
print()
p4 = Polynomial([3, 4, 5, 6, 10, 23])
print(p3 * p4)
print()
for i in range(len((p3 * p4).coefficients)):
    print((p3 * p4).coeff(i))
