# You will learn about the import statement later;
# for now, think of import turtle as importing functions in the turtle module, containing graphic functions;
# see the document at https://docs.python.org/3/library/turtle.html
import turtle
import time

# set up pen before draw the 6 hexagons
turtle.setheading(0)
turtle.pensize(5)

# draw blue hexagon
turtle.penup()
turtle.color("blue")
turtle.goto(0, 0)
turtle.pendown()
turtle.left(30)
for i in range(6):
    turtle.forward(100)
    turtle.left(60)

# draw red hexagon
turtle.penup()
turtle.color("red")
turtle.pendown()
turtle.left(90)
for i in range(6):
    turtle.forward(100)
    turtle.left(60)

# draw yellow hexagon
turtle.penup()
turtle.color("yellow")
turtle.pendown()
turtle.left(90)
for i in range(6):
    turtle.forward(100)
    turtle.left(60)

# draw green hexagon
turtle.penup()
turtle.color("green")
turtle.pendown()
turtle.left(90)
for i in range(6):
    turtle.forward(100)
    turtle.left(60)

# clear the first picture before draw the UK flag
time.sleep(3)
turtle.clear()
turtle.pensize(1)
turtle.setheading(0)

# draw UK flag
# draw red rectangle as a frame
turtle.penup()
turtle.color("#c8102e")
turtle.fillcolor("#c8102e")
turtle.left(180)
turtle.forward(300)
turtle.right(90)
turtle.forward(150)
turtle.right(90)
turtle.pendown()
turtle.begin_fill()
for i in range(2):
    turtle.forward(600)
    turtle.right(90)
    turtle.forward(300)
    turtle.right(90)
turtle.end_fill()

# draw 4 white rectangle at the edge
def white_rectangle():
    for i in range(2):
        turtle.forward(270)
        turtle.right(90)
        turtle.forward(120)
        turtle.right(90)
turtle.penup()
turtle.color("white")
turtle.fillcolor("white")
turtle.pendown()
turtle.begin_fill()
white_rectangle()
turtle.end_fill()
turtle.penup()
turtle.forward(330)
turtle.pendown()
turtle.begin_fill()
white_rectangle()
turtle.end_fill()
turtle.penup()
turtle.right(90)
turtle.forward(180)
turtle.left(90)
turtle.pendown()
turtle.begin_fill()
white_rectangle()
turtle.end_fill()
turtle.penup()
turtle.left(180)
turtle.forward(330)
turtle.right(180)
turtle.pendown()
turtle.begin_fill()
white_rectangle()
turtle.end_fill()

# draw 4 red lines
# 1st red line
turtle.penup()
turtle.color("#c8102e")
turtle.fillcolor("#c8102e")
turtle.left(90)
turtle.forward(180)
turtle.right(180)
turtle.pendown()
turtle.begin_fill()
turtle.forward(100)
turtle.left(90)
turtle.forward(200)
turtle.end_fill()
turtle.color("white")
turtle.fillcolor("white")
turtle.penup()
turtle.left(180)
turtle.forward(40)
turtle.pendown()
turtle.begin_fill()
turtle.forward(160)
turtle.right(90)
turtle.forward(80)
turtle.end_fill()

# 2nd red line
turtle.penup()
turtle.color("#c8102e")
turtle.fillcolor("#c8102e")
turtle.forward(20)
turtle.right(90)
turtle.forward(560)
turtle.pendown()
turtle.begin_fill()
turtle.forward(40)
turtle.right(90)
turtle.forward(100)
turtle.right(90)
turtle.forward(240)
turtle.end_fill()
turtle.penup()
turtle.right(180)
turtle.forward(40)
turtle.color("white")
turtle.fillcolor("white")
turtle.pendown()
turtle.begin_fill()
turtle.forward(200)
turtle.left(90)
turtle.forward(100)
turtle.end_fill()

# 3rd red line
turtle.penup()
turtle.color("#c8102e")
turtle.fillcolor("#c8102e")
turtle.left(180)
turtle.forward(200)
turtle.right(90)
turtle.forward(200)
turtle.left(180)
turtle.pendown()
turtle.begin_fill()
turtle.forward(200)
turtle.right(90)
turtle.forward(100)
turtle.end_fill()
turtle.penup()
turtle.left(180)
turtle.forward(20)
turtle.color("white")
turtle.fillcolor("white")
turtle.pendown()
turtle.begin_fill()
turtle.forward(80)
turtle.left(90)
turtle.forward(160)
turtle.end_fill()

# 4th red line
turtle.penup()
turtle.color("#c8102e")
turtle.fillcolor("#c8102e")
turtle.forward(200)
turtle.pendown()
turtle.begin_fill()
turtle.forward(240)
turtle.left(90)
turtle.forward(100)
turtle.left(90)
turtle.forward(40)
turtle.end_fill()
turtle.penup()
turtle.left(180)
turtle.forward(40)
turtle.right(90)
turtle.color("white")
turtle.fillcolor("white")
turtle.pendown()
turtle.begin_fill()
turtle.forward(100)
turtle.right(90)
turtle.forward(200)
turtle.end_fill()


# before draw 8 blue triangles, set turtle to the position
turtle.penup()
turtle.left(180)
turtle.forward(200)
turtle.right(90)
turtle.forward(200)
turtle.right(90)
turtle.forward(70)

# 1st blue triangle
turtle.color("#012169")
turtle.fillcolor("#012169")
turtle.pendown()
turtle.begin_fill()
turtle.forward(180)
turtle.right(90)
turtle.forward(90)
turtle.end_fill()

# 2nd blue triangle
turtle.penup()
turtle.left(90)
turtle.forward(100)
turtle.left(90)
turtle.pendown()
turtle.begin_fill()
turtle.forward(90)
turtle.right(90)
turtle.forward(180)
turtle.end_fill()

# 3rd blue triangle
turtle.penup()
turtle.forward(70)
turtle.right(90)
turtle.forward(30)
turtle.pendown()
turtle.begin_fill()
turtle.forward(70)
turtle.right(90)
turtle.forward(130)
turtle.end_fill()

# 4th blue triangle
turtle.penup()
turtle.left(90)
turtle.forward(100)
turtle.left(90)
turtle.pendown()
turtle.begin_fill()
turtle.forward(130)
turtle.right(90)
turtle.forward(70)
turtle.end_fill()

# 5th blue triangle
turtle.penup()
turtle.forward(30)
turtle.right(90)
turtle.forward(70)
turtle.pendown()
turtle.begin_fill()
turtle.forward(180)
turtle.right(90)
turtle.forward(90)
turtle.end_fill()

# 6th blue triangle
turtle.penup()
turtle.left(90)
turtle.forward(100)
turtle.left(90)
turtle.pendown()
turtle.begin_fill()
turtle.forward(90)
turtle.right(90)
turtle.forward(180)
turtle.end_fill()

# 7th blue triangle
turtle.penup()
turtle.forward(70)
turtle.right(90)
turtle.forward(30)
turtle.pendown()
turtle.begin_fill()
turtle.forward(70)
turtle.right(90)
turtle.forward(130)
turtle.end_fill()

# 8th blue triangle
turtle.penup()
turtle.left(90)
turtle.forward(100)
turtle.left(90)
turtle.pendown()
turtle.begin_fill()
turtle.forward(130)
turtle.right(90)
turtle.forward(70)
turtle.end_fill()


# clear the second picture before draw the traffic light
time.sleep(3)
turtle.penup()
turtle.clear()
turtle.pensize(1)
turtle.setheading(0)
turtle.goto(0, 0)

# draw traffic light
turtle.color("yellow")
turtle.fillcolor("yellow")
turtle.left(90)
turtle.forward(150)
turtle.pendown()
turtle.right(135)
turtle.begin_fill()
for i in range(4):
    turtle.forward(250)
    turtle.right(90)
turtle.end_fill()
turtle.penup()
turtle.right(45)
turtle.forward(20)
turtle.color("black")
turtle.pensize(3)
turtle.pendown()
turtle.left(45)
for i in range(4):
    turtle.forward(220)
    turtle.right(90)
turtle.pensize(1)
turtle.penup()
turtle.right(45)
turtle.forward(60)
turtle.left(90)
turtle.forward(40)
turtle.pendown()
turtle.begin_fill()
for i in range(2):
    turtle.right(90)
    turtle.forward(190)
    turtle.right(90)
    turtle.forward(80)
turtle.end_fill()
turtle.penup()
turtle.color("red")
turtle.fillcolor("red")
turtle.left(180)
turtle.forward(65)
turtle.left(90)
turtle.forward(35)
turtle.pendown()
turtle.begin_fill()
turtle.circle(25)
turtle.end_fill()
turtle.penup()
turtle.forward(60)
turtle.color("yellow")
turtle.fillcolor("yellow")
turtle.pendown()
turtle.begin_fill()
turtle.circle(25)
turtle.end_fill()
turtle.penup()
turtle.forward(60)
turtle.color("green")
turtle.fillcolor("green")
turtle.pendown()
turtle.begin_fill()
turtle.circle(25)
turtle.end_fill()
turtle.penup()

# hold the window; close it by clicking the window close 'x' mark
turtle.done()
